;; (setq inferior-lisp-program "/usr/local/bin/sbcl")
(setq inferior-lisp-program "/usr/local/Cellar/clozure-cl/1.10/bin/ccl64")
(slime-setup '(slime-company slime-fancy slime-banner))
(defun my-slime-mode-hook()
  (setq slime-protocol-version 'ignore)
  (setq slime-net-coding-system 'utf-8-unix)
  (slime-setup '(slime-repl slime-fuzzy))
  (setq slime-complete-symbol*-fancy t)
  (setq slime-complete-symbol-function 'slime-fuzzy-complete-symbol)
  (slime-setup)
  (set-up-slime-hippie-expand)
  (set-up-slime-ac t))
(add-hook 'slime-mode-hook 'my-slime-mode-hook)
(add-hook 'slime-repl-mode-hook 'rainbow-delimiters-mode)
(provide 'init-slime)
