;; (setq inferior-lisp-program "/usr/local/bin/sbcl")
(setq inferior-lisp-program "/usr/local/Cellar/clozure-cl/1.9/bin/ccl64")
(setq slime-contribs '(slime-fancy))
(slime-setup)
(defun my-slime-mode-hook()
  (setq slime-protocol-version 'ignore)
  (setq slime-net-coding-system 'utf-8-unix)
  (slime-setup '(slime-repl slime-fuzzy))
  (setq slime-complete-symbol*-fancy t)
  (setq slime-complete-symbol-function 'slime-fuzzy-complete-symbol)
  (slime-setup)
  (set-up-slime-hippie-expand)
  (set-up-slime-ac t)
  )
(add-hook 'slime-mode-hook 'my-slime-mode-hook)
(provide 'init-slime)
